[calibration]
; 棋盘格横向内角点数量，范围 2～100。
boardWidth=11
; 棋盘格纵向内角点数量，范围 2～100。
boardHeight=8
; 棋盘格单格宽度，单位毫米，范围 0.001～10000。
squareWidth=15
; 棋盘格单格高度，单位毫米，范围 0.001～10000。
squareHeight=15
; 标定图像起始索引；-1 表示不限制。
imageBegin=-1
; 标定图像结束索引；-1 表示不限制。
imageEnd=-1
