# 构建路径统一读取 config；不写配置文件，不依赖本机预设中的重复路径。
set(HTMSR_ENVIRONMENT_FILE "${CMAKE_CURRENT_SOURCE_DIR}/config/environment.ini" CACHE FILEPATH "HTMSR dependency configuration")
get_filename_component(HTMSR_ENVIRONMENT_FILE "${HTMSR_ENVIRONMENT_FILE}" ABSOLUTE)
if(NOT EXISTS "${HTMSR_ENVIRONMENT_FILE}")
    message(FATAL_ERROR "Missing dependency configuration: ${HTMSR_ENVIRONMENT_FILE}")
endif()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${HTMSR_ENVIRONMENT_FILE}")
get_filename_component(htmsr_environment_directory "${HTMSR_ENVIRONMENT_FILE}" DIRECTORY)
file(STRINGS "${HTMSR_ENVIRONMENT_FILE}" htmsr_environment_lines ENCODING UTF-8)
set(htmsr_environment_section "")
set(htmsr_environment_keys)
foreach(htmsr_environment_line IN LISTS htmsr_environment_lines)
    string(STRIP "${htmsr_environment_line}" htmsr_environment_line)
    if(htmsr_environment_line STREQUAL "" OR htmsr_environment_line MATCHES "^[;#]")
        continue()
    elseif(htmsr_environment_line MATCHES "^\\[([^]]+)\\]$")
        set(htmsr_environment_section "${CMAKE_MATCH_1}")
    elseif(htmsr_environment_section STREQUAL "build")
        if(NOT htmsr_environment_line MATCHES "^([A-Za-z_][A-Za-z0-9_]*)=(.*)$")
            message(FATAL_ERROR "Invalid [build] entry in ${HTMSR_ENVIRONMENT_FILE}: ${htmsr_environment_line}")
        endif()
        set(htmsr_environment_key "${CMAKE_MATCH_1}")
        set(htmsr_environment_value "${CMAKE_MATCH_2}")
        string(STRIP "${htmsr_environment_value}" htmsr_environment_value)
        if(htmsr_environment_key IN_LIST htmsr_environment_keys)
            message(FATAL_ERROR "Duplicate [build] key in ${HTMSR_ENVIRONMENT_FILE}: ${htmsr_environment_key}")
        endif()
        list(APPEND htmsr_environment_keys "${htmsr_environment_key}")
        set("htmsr_environment_value_${htmsr_environment_key}" "${htmsr_environment_value}")
    endif()
endforeach()

# 先收集，再应用 Debug 覆盖，使配置项的排列顺序不影响最终结果。
set(htmsr_environment_effective_keys)
foreach(htmsr_environment_key IN LISTS htmsr_environment_keys)
    if(NOT htmsr_environment_key MATCHES "_DEBUG$")
        list(APPEND htmsr_environment_effective_keys "${htmsr_environment_key}")
        set("htmsr_environment_effective_${htmsr_environment_key}" "${htmsr_environment_value_${htmsr_environment_key}}")
    endif()
endforeach()
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    foreach(htmsr_environment_key IN LISTS htmsr_environment_keys)
        if(htmsr_environment_key MATCHES "_DEBUG$" AND NOT htmsr_environment_value_${htmsr_environment_key} STREQUAL "")
            string(REGEX REPLACE "_DEBUG$" "" htmsr_environment_base_key "${htmsr_environment_key}")
            list(APPEND htmsr_environment_effective_keys "${htmsr_environment_base_key}")
            set("htmsr_environment_effective_${htmsr_environment_base_key}" "${htmsr_environment_value_${htmsr_environment_key}}")
        endif()
    endforeach()
endif()
list(REMOVE_DUPLICATES htmsr_environment_effective_keys)
list(SORT htmsr_environment_effective_keys)
set(htmsr_environment_signature "${HTMSR_ENVIRONMENT_FILE}\n${CMAKE_CURRENT_SOURCE_DIR}\n${CMAKE_BUILD_TYPE}\n")
foreach(htmsr_environment_key IN LISTS htmsr_environment_effective_keys)
    string(APPEND htmsr_environment_signature "${htmsr_environment_key}=${htmsr_environment_effective_${htmsr_environment_key}}\n")
endforeach()
string(SHA256 htmsr_environment_fingerprint "${htmsr_environment_signature}")
if(NOT HTMSR_BUILD_ENVIRONMENT_FINGERPRINT STREQUAL htmsr_environment_fingerprint)
    # 依赖根目录变化后，清除上次 find_package/find_library 的结果，防止混用旧库。
    get_cmake_property(htmsr_environment_cached_variables CACHE_VARIABLES)
    foreach(htmsr_environment_cached_variable IN LISTS htmsr_environment_cached_variables)
        if(htmsr_environment_cached_variable MATCHES "^(Qt5.*|OpenCV.*|PCL.*|VTK.*|Eigen.*|EIGEN.*|Boost.*|BOOST.*|boost_.*|Qhull.*|QHULL.*|FLANN.*|OPENNI.*|OpenNI.*|HIK_MVS.*|HTMSR_EIGEN_INCLUDE_DIR)$")
            unset("${htmsr_environment_cached_variable}" CACHE)
            unset("${htmsr_environment_cached_variable}")
        endif()
    endforeach()
    message(STATUS "HTMSR: dependency configuration changed; refreshed dependency search cache")
endif()

foreach(htmsr_environment_key IN LISTS htmsr_environment_effective_keys)
    set(htmsr_environment_value "${htmsr_environment_effective_${htmsr_environment_key}}")
    if(htmsr_environment_key MATCHES "^(Qt5_DIR|OpenCV_DIR|PCL_DIR|VTK_DIR|HTMSR_EIGEN_INCLUDE_DIR|HIK_MVS_ROOT|HIK_MVS_RUNTIME_DIR|OPENNI2_LIBRARY|CMAKE_PREFIX_PATH)$")
        set(htmsr_environment_absolute_paths)
        foreach(htmsr_environment_path IN LISTS htmsr_environment_value)
            if(NOT htmsr_environment_path STREQUAL "")
                get_filename_component(htmsr_environment_path "${htmsr_environment_path}" ABSOLUTE BASE_DIR "${htmsr_environment_directory}")
                list(APPEND htmsr_environment_absolute_paths "${htmsr_environment_path}")
            endif()
        endforeach()
        set(htmsr_environment_value "${htmsr_environment_absolute_paths}")
    endif()
    set("${htmsr_environment_key}" "${htmsr_environment_value}" CACHE STRING "From config/environment.ini" FORCE)
    set("${htmsr_environment_key}" "${htmsr_environment_value}")
endforeach()

# CMAKE_PREFIX_PATH 只作为可选补充；常见依赖及 PCL 的第三方搜索目录自动推导。
set(htmsr_environment_prefixes)
if("CMAKE_PREFIX_PATH" IN_LIST htmsr_environment_effective_keys)
    set(htmsr_environment_prefixes "${CMAKE_PREFIX_PATH}")
endif()
foreach(htmsr_environment_key Qt5_DIR OpenCV_DIR PCL_DIR VTK_DIR HTMSR_EIGEN_INCLUDE_DIR)
    if(${htmsr_environment_key})
        list(APPEND htmsr_environment_prefixes "${${htmsr_environment_key}}")
    endif()
endforeach()
set(htmsr_environment_pcl_root "${PCL_DIR}")
foreach(htmsr_environment_level RANGE 0 4)
    if(EXISTS "${htmsr_environment_pcl_root}/3rdParty")
        list(APPEND htmsr_environment_prefixes "${htmsr_environment_pcl_root}")
        file(GLOB htmsr_environment_third_party_prefixes LIST_DIRECTORIES true
            "${htmsr_environment_pcl_root}/3rdParty/*"
            "${htmsr_environment_pcl_root}/3rdParty/*/cmake"
            "${htmsr_environment_pcl_root}/3rdParty/*/lib/cmake/*"
            "${htmsr_environment_pcl_root}/3rdParty/*/share/*/cmake")
        foreach(htmsr_environment_third_party_prefix IN LISTS htmsr_environment_third_party_prefixes)
            if(IS_DIRECTORY "${htmsr_environment_third_party_prefix}")
                list(APPEND htmsr_environment_prefixes "${htmsr_environment_third_party_prefix}")
            endif()
        endforeach()
        break()
    endif()
    get_filename_component(htmsr_environment_parent "${htmsr_environment_pcl_root}" DIRECTORY)
    if(htmsr_environment_parent STREQUAL htmsr_environment_pcl_root)
        break()
    endif()
    set(htmsr_environment_pcl_root "${htmsr_environment_parent}")
endforeach()
list(FILTER htmsr_environment_prefixes EXCLUDE REGEX "^$")
list(REMOVE_DUPLICATES htmsr_environment_prefixes)
set(CMAKE_PREFIX_PATH "${htmsr_environment_prefixes}" CACHE STRING "Automatically derived from config/environment.ini" FORCE)
set(CMAKE_PREFIX_PATH "${htmsr_environment_prefixes}")
set(HTMSR_BUILD_ENVIRONMENT_FINGERPRINT "${htmsr_environment_fingerprint}" CACHE INTERNAL "Last dependency configuration" FORCE)
message(STATUS "HTMSR: loaded build environment from ${HTMSR_ENVIRONMENT_FILE}")
